### ISSUE TITLE
Typo in release

### ISSUE THREAD

**Issue by nickdunn** [lukeholder/craft-inflect#4]
I was getting a PHP error:

    Undefined property: Craft\InflectTwigExtension::$inflectornflector

Should `$this->inflectornflector` read `$this->inflector`? Using the latest release zip.

**Comment by nickdunn** [comment]
Even after making this change, the plugin didn't work for me. 

    {{ 'people'|pluralize(1) }}

Would still return `people`.

**Comment by lukeholder** [comment]
looking into it now, thanks for reporting.

**Comment by auralon** [comment]
I can confirm this.  Was about to submit a pull request, but realised that the current source is not affected, it's just the 1.2 release zip that contains this bug.

**Comment by lukeholder** [comment]
Release fixed in 1.4 - sorry for the delay. 
https://github.com/lukeholder/craft-inflect/releases

**Comment by auralon** [comment]
No sweat, thank you for you work! :+1:
