### ISSUE TITLE
Pluralize doesn't accept $num arg

### ISSUE THREAD

**Issue by timkelty** [lukeholder/craft-inflect#8]
Not sure if `icanboogie/inflector` changed this, but pluralize just _always_ pluralizes now, so it doesn't take an argument like your docs say.

**Comment by lukeholder** [comment]
Not able to reproduce:

```
{{ 'people'|pluralize(1) }}
{# outputs person #}

{{ 'people'|pluralize(2) }}
{# outputs people #}
```

**Comment by lukeholder** [comment]
Only thing I can think of is the word not being caught in the dictionary matcher.
